# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference_service/image_classification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inference_service/image_classification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,inference_service/image_classification.proto\x12\x14image_classification\"8\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x14\n\x0cimage_format\x18\x02 \x01(\t\"S\n\x16\x43lassificationResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x16\n\x0einference_time\x18\x03 \x01(\x02\"\x14\n\x12HealthCheckRequest\":\n\x13HealthCheckResponse\x12\x12\n\nis_healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2\xe7\x01\n\x1aImageClassificationService\x12\x63\n\rClassifyImage\x12\".image_classification.ImageRequest\x1a,.image_classification.ClassificationResponse\"\x00\x12\x64\n\x0bHealthCheck\x12(.image_classification.HealthCheckRequest\x1a).image_classification.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_service.image_classification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=70
  _globals['_IMAGEREQUEST']._serialized_end=126
  _globals['_CLASSIFICATIONRESPONSE']._serialized_start=128
  _globals['_CLASSIFICATIONRESPONSE']._serialized_end=211
  _globals['_HEALTHCHECKREQUEST']._serialized_start=213
  _globals['_HEALTHCHECKREQUEST']._serialized_end=233
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=235
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=293
  _globals['_IMAGECLASSIFICATIONSERVICE']._serialized_start=296
  _globals['_IMAGECLASSIFICATIONSERVICE']._serialized_end=527
# @@protoc_insertion_point(module_scope)
