# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from inference_service import image_classification_pb2 as inference__service_dot_image__classification__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inference_service/image_classification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageClassificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyImage = channel.unary_unary(
                '/image_classification.ImageClassificationService/ClassifyImage',
                request_serializer=inference__service_dot_image__classification__pb2.ImageRequest.SerializeToString,
                response_deserializer=inference__service_dot_image__classification__pb2.ClassificationResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/image_classification.ImageClassificationService/HealthCheck',
                request_serializer=inference__service_dot_image__classification__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=inference__service_dot_image__classification__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ImageClassificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClassifyImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageClassificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyImage,
                    request_deserializer=inference__service_dot_image__classification__pb2.ImageRequest.FromString,
                    response_serializer=inference__service_dot_image__classification__pb2.ClassificationResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=inference__service_dot_image__classification__pb2.HealthCheckRequest.FromString,
                    response_serializer=inference__service_dot_image__classification__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image_classification.ImageClassificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('image_classification.ImageClassificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageClassificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClassifyImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/image_classification.ImageClassificationService/ClassifyImage',
            inference__service_dot_image__classification__pb2.ImageRequest.SerializeToString,
            inference__service_dot_image__classification__pb2.ClassificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/image_classification.ImageClassificationService/HealthCheck',
            inference__service_dot_image__classification__pb2.HealthCheckRequest.SerializeToString,
            inference__service_dot_image__classification__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
