# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_classification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

class ImageRequest(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _descriptor.FileDescriptor(
        name='image_classification.proto',
        package='image_classification',
        syntax='proto3',
        serialized_pb=_b('\n\x1aimage_classification.proto\x12\x14image_classification\"7\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x13\n\x0bimage_format\x18\x02 \x01(\t\"X\n\x15\x43lassificationResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x16\n\x0einference_time\x18\x03 \x01(\x02\"\x12\n\x10HealthCheckRequest\"1\n\x14HealthCheckResponse\x12\x12\n\nis_healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2\xc1\x01\n\x19ImageClassificationService\x12\x61\n\x0c\x43lassifyImage\x12\".image_classification.ImageRequest\x1a+.image_classification.ClassificationResponse\x12\x61\n\x0bHealthCheck\x12&.image_classification.HealthCheckRequest\x1a*.image_classification.HealthCheckResponseb\x06proto3')
